:global:
  componentName: appuio-cloud-reporting
  githubUrl: https://github.com/appuio/component-appuio-cloud-reporting
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults

.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
